# Homebrew Configure
eval "$(/opt/homebrew/bin/brew shellenv)"

# Path to Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set oh-my-zsh theme
ZSH_THEME="robbyrussell"

# Config oh-my-zsh plugins
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

# Load oh-my-zsh
source ~/.oh-my-zsh/oh-my-zsh.sh

# Key binding
bindkey "^Y" autosuggest-accept
bindkey '^E' autosuggest-clear

# [[ User Configuration ]]
export MAC_CONF_DIR="$HOME/Dotfiles/MacConf"

# Quick Command
cdd() {
  local dir
    dir=$(fd --type d --hidden --exclude .git | fzf \
    --height 40% \
    --reverse \
    --border \
    --prompt "Select Dir: "
  )
  if [[ -n "$dir" ]]; then
    cd "$dir"
  fi
}
of() {
  local file
  file=$(fd --type f --hidden --exclude .git | fzf \
    --preview 'cat {}' \
    --preview-window right \
    --reverse \
    --border \
    --prompt "Choose File: "
  )
  if [[ -n "$file" ]]; then
    nvim "$file"
  fi
}

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Config nvm
export NVM_DIR="$HOME/.nvm"
    [ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"
    [ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm"
